import React from 'react'

import Navbar from './Navbar'
import Footer from './Footer'

export default function Homepage() {
    return (
        <>
            <Navbar />
            <div className='pb-20 p-5'>
                <h1 className='text-2xl'>Home Content</h1>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo laoreet sit amet cursus sit amet dictum sit amet. Est placerat in egestas erat imperdiet sed. Dignissim sodales ut eu sem integer vitae justo eget. Libero enim sed faucibus turpis in eu mi. Pellentesque diam volutpat commodo sed egestas egestas. Sit amet justo donec enim diam vulputate. Sit amet nulla facilisi morbi tempus iaculis. Urna cursus eget nunc scelerisque viverra. Mus mauris vitae ultricies leo integer malesuada nunc vel. Et netus et malesuada fames ac turpis egestas. Sit amet nisl purus in. Purus in massa tempor nec feugiat nisl pretium fusce id. Ut faucibus pulvinar elementum integer enim neque volutpat. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Nulla pharetra diam sit amet nisl suscipit adipiscing.

                    Orci sagittis eu volutpat odio facilisis mauris sit amet. Purus semper eget duis at tellus at urna condimentum mattis. In hac habitasse platea dictumst vestibulum rhoncus est. Leo urna molestie at elementum eu facilisis. Dictum at tempor commodo ullamcorper a lacus vestibulum. Suscipit tellus mauris a diam. Turpis egestas pretium aenean pharetra. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Lorem donec massa sapien faucibus et. Amet nisl suscipit adipiscing bibendum est ultricies integer. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Id leo in vitae turpis massa sed elementum. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Molestie nunc non blandit massa enim nec. Mauris nunc congue nisi vitae suscipit tellus mauris a. A arcu cursus vitae congue mauris rhoncus aenean. Mauris commodo quis imperdiet massa tincidunt nunc.

                    Arcu dui vivamus arcu felis bibendum ut tristique. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Porta nibh venenatis cras sed felis eget velit aliquet. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Eget lorem dolor sed viverra ipsum nunc. Mattis pellentesque id nibh tortor id aliquet. In fermentum posuere urna nec tincidunt praesent. Nulla aliquet enim tortor at. Mauris nunc congue nisi vitae suscipit tellus. Mauris vitae ultricies leo integer malesuada nunc vel risus.

                    Semper quis lectus nulla at volutpat diam ut venenatis. Sit amet porttitor eget dolor. Id diam maecenas ultricies mi. Nisi est sit amet facilisis magna etiam tempor orci eu. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Dolor sit amet consectetur adipiscing. Eu sem integer vitae justo eget. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Fermentum iaculis eu non diam phasellus vestibulum. Tincidunt vitae semper quis lectus nulla at volutpat diam. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. A scelerisque purus semper eget duis at tellus at. Fermentum dui faucibus in ornare. Aliquam vestibulum morbi blandit cursus risus at. Magna eget est lorem ipsum dolor sit amet consectetur.

                    Ullamcorper dignissim cras tincidunt lobortis feugiat. Erat velit scelerisque in dictum non consectetur a erat. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Lacinia quis vel eros donec ac odio tempor orci dapibus. Morbi tristique senectus et netus et malesuada. Mauris augue neque gravida in fermentum et. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Magna sit amet purus gravida quis blandit. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Ultricies tristique nulla aliquet enim tortor at auctor. At in tellus integer feugiat scelerisque varius morbi enim. Vulputate mi sit amet mauris commodo quis. Sit amet purus gravida quis.

                    Lacus vestibulum sed arcu non odio euismod lacinia. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Justo nec ultrices dui sapien eget mi proin sed libero. Tellus pellentesque eu tincidunt tortor. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Tincidunt lobortis feugiat vivamus at augue eget arcu. Urna duis convallis convallis tellus id interdum. Ut pharetra sit amet aliquam id diam. Auctor elit sed vulputate mi sit. Tristique senectus et netus et malesuada fames ac turpis.

                    Tellus cras adipiscing enim eu turpis egestas pretium. Amet tellus cras adipiscing enim eu turpis egestas. A iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Nibh cras pulvinar mattis nunc sed blandit libero. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Aliquam ut porttitor leo a diam sollicitudin. Nulla facilisi cras fermentum odio eu feugiat pretium nibh. Donec et odio pellentesque diam volutpat commodo. Semper eget duis at tellus at urna condimentum mattis pellentesque. Diam quam nulla porttitor massa id. Sagittis eu volutpat odio facilisis. Magna etiam tempor orci eu lobortis elementum nibh tellus. Sed augue lacus viverra vitae congue eu. Ut eu sem integer vitae justo eget magna. Tellus pellentesque eu tincidunt tortor aliquam nulla. Aliquet porttitor lacus luctus accumsan tortor. Aliquet enim tortor at auctor urna nunc id cursus metus.

                    Vitae semper quis lectus nulla at volutpat. Netus et malesuada fames ac turpis egestas maecenas pharetra. Id velit ut tortor pretium viverra. Posuere sollicitudin aliquam ultrices sagittis. Arcu bibendum at varius vel pharetra. Natoque penatibus et magnis dis parturient. Ultrices dui sapien eget mi proin sed libero enim sed. Semper risus in hendrerit gravida rutrum. Neque aliquam vestibulum morbi blandit cursus risus at ultrices. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Cursus mattis molestie a iaculis at. Suscipit tellus mauris a diam maecenas sed. Aliquam id diam maecenas ultricies mi eget mauris pharetra. Mi bibendum neque egestas congue quisque egestas diam in arcu.

                    Eget est lorem ipsum dolor. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Turpis massa sed elementum tempus egestas sed sed risus pretium. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Quam nulla porttitor massa id. Egestas tellus rutrum tellus pellentesque eu. Faucibus et molestie ac feugiat sed. Vulputate odio ut enim blandit volutpat maecenas volutpat. Facilisis leo vel fringilla est ullamcorper. Pretium quam vulputate dignissim suspendisse. Ultrices vitae auctor eu augue ut lectus arcu bibendum. Purus ut faucibus pulvinar elementum integer. Nunc congue nisi vitae suscipit. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Vitae suscipit tellus mauris a. Turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet. In ornare quam viverra orci sagittis eu volutpat odio. Fusce ut placerat orci nulla pellentesque dignissim enim sit amet. Vitae aliquet nec ullamcorper sit amet risus nullam. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus.

                    Etiam tempor orci eu lobortis elementum nibh tellus molestie. Gravida dictum fusce ut placerat. Facilisi etiam dignissim diam quis enim lobortis scelerisque. Donec ultrices tincidunt arcu non sodales neque sodales ut. Adipiscing elit ut aliquam purus. Et egestas quis ipsum suspendisse ultrices. Odio ut sem nulla pharetra diam. Aenean euismod elementum nisi quis eleifend quam. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Porttitor lacus luctus accumsan tortor posuere ac. Eget nullam non nisi est sit amet facilisis. Et tortor consequat id porta nibh venenatis cras. Tempus egestas sed sed risus pretium quam vulputate dignissim. Elit pellentesque habitant morbi tristique. Tincidunt augue interdum velit euismod in pellentesque.

                    Bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida. Sed viverra ipsum nunc aliquet bibendum enim. Arcu bibendum at varius vel pharetra vel turpis. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Vitae suscipit tellus mauris a. Scelerisque felis imperdiet proin fermentum leo. Congue eu consequat ac felis donec et odio pellentesque diam. Odio tempor orci dapibus ultrices in. Turpis massa tincidunt dui ut ornare lectus sit amet est. Amet mauris commodo quis imperdiet. Mauris pharetra et ultrices neque ornare aenean euismod. Interdum velit laoreet id donec ultrices. Commodo elit at imperdiet dui accumsan sit amet nulla. Pulvinar etiam non quam lacus suspendisse. Magna sit amet purus gravida quis. At ultrices mi tempus imperdiet nulla malesuada. Magna eget est lorem ipsum dolor sit amet consectetur. Nisi quis eleifend quam adipiscing vitae.

                    Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Elementum eu facilisis sed odio morbi quis commodo. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Lorem donec massa sapien faucibus et molestie ac feugiat. Ullamcorper malesuada proin libero nunc consequat interdum. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Lobortis elementum nibh tellus molestie nunc non blandit massa. Viverra adipiscing at in tellus integer feugiat scelerisque varius morbi. Tristique senectus et netus et malesuada fames. Elementum curabitur vitae nunc sed velit. Porttitor lacus luctus accumsan tortor posuere ac ut consequat. Etiam dignissim diam quis enim lobortis. Ultrices tincidunt arcu non sodales neque. Bibendum enim facilisis gravida neque convallis a cras semper. Sed risus pretium quam vulputate dignissim suspendisse in est.

                    Pulvinar etiam non quam lacus suspendisse faucibus. Tellus id interdum velit laoreet id donec ultrices tincidunt. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Justo eget magna fermentum iaculis eu. Porta lorem mollis aliquam ut porttitor leo. Morbi quis commodo odio aenean sed adipiscing diam. Viverra accumsan in nisl nisi scelerisque eu ultrices. Risus ultricies tristique nulla aliquet enim tortor at auctor. Vitae congue mauris rhoncus aenean vel elit scelerisque. Cursus mattis molestie a iaculis at erat. Ut lectus arcu bibendum at. Felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Cras semper auctor neque vitae tempus quam. Augue interdum velit euismod in.

                    Viverra ipsum nunc aliquet bibendum enim. At quis risus sed vulputate odio ut enim blandit. Sed tempus urna et pharetra pharetra. Eu consequat ac felis donec et. Feugiat in fermentum posuere urna nec. Auctor augue mauris augue neque gravida in. Aliquam etiam erat velit scelerisque in. Risus ultricies tristique nulla aliquet enim tortor at auctor. Sed ullamcorper morbi tincidunt ornare massa eget egestas. Nec dui nunc mattis enim ut.

                    Hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Amet est placerat in egestas erat imperdiet sed euismod. Bibendum arcu vitae elementum curabitur. Enim facilisis gravida neque convallis a. Sagittis id consectetur purus ut faucibus pulvinar elementum integer enim. Scelerisque varius morbi enim nunc faucibus a. Scelerisque felis imperdiet proin fermentum leo vel orci. Dignissim enim sit amet venenatis urna cursus eget nunc scelerisque. Ullamcorper sit amet risus nullam. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Enim nec dui nunc mattis. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Platea dictumst vestibulum rhoncus est. Enim ut tellus elementum sagittis vitae. Elementum tempus egestas sed sed risus. Neque ornare aenean euismod elementum nisi. Fermentum odio eu feugiat pretium nibh. Sem integer vitae justo eget. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi nullam.

                    Eu lobortis elementum nibh tellus molestie. In tellus integer feugiat scelerisque varius morbi enim. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. In hendrerit gravida rutrum quisque non tellus orci. In est ante in nibh. Erat velit scelerisque in dictum non consectetur a. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Sit amet tellus cras adipiscing. Arcu non sodales neque sodales. Est lorem ipsum dolor sit amet consectetur adipiscing. Quis auctor elit sed vulputate mi sit amet mauris commodo. Nibh cras pulvinar mattis nunc sed blandit libero volutpat. Est ante in nibh mauris.

                    Pellentesque id nibh tortor id aliquet. Condimentum vitae sapien pellentesque habitant morbi tristique. Proin nibh nisl condimentum id venenatis a condimentum. Risus nec feugiat in fermentum posuere urna. Consequat id porta nibh venenatis cras sed. Arcu odio ut sem nulla pharetra diam sit. Donec et odio pellentesque diam volutpat commodo sed. Sit amet consectetur adipiscing elit duis tristique sollicitudin. Id ornare arcu odio ut sem nulla pharetra. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ultrices eros in cursus turpis massa tincidunt dui ut. Leo integer malesuada nunc vel risus commodo viverra maecenas. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Ante in nibh mauris cursus mattis molestie a. Amet cursus sit amet dictum sit. Ut tortor pretium viverra suspendisse potenti nullam ac tortor. Dignissim suspendisse in est ante in nibh mauris cursus. Lorem ipsum dolor sit amet consectetur.

                    Mauris augue neque gravida in fermentum et. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. Nisl vel pretium lectus quam id leo in vitae turpis. Congue mauris rhoncus aenean vel elit. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a. In aliquam sem fringilla ut morbi tincidunt augue. Duis convallis convallis tellus id interdum velit laoreet id donec. Elementum sagittis vitae et leo duis ut diam quam. Duis at tellus at urna condimentum mattis pellentesque id. Pellentesque adipiscing commodo elit at imperdiet. In arcu cursus euismod quis. Eros donec ac odio tempor orci dapibus ultrices in iaculis. Ultrices eros in cursus turpis massa. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Dignissim sodales ut eu sem integer. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod.

                    Sollicitudin nibh sit amet commodo nulla facilisi nullam. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Nunc consequat interdum varius sit amet mattis vulputate enim. Id eu nisl nunc mi ipsum faucibus vitae aliquet. Egestas diam in arcu cursus euismod. Morbi tristique senectus et netus et. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Id faucibus nisl tincidunt eget.

                    Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Est velit egestas dui id ornare arcu odio. Sed velit dignissim sodales ut eu sem integer vitae. Volutpat blandit aliquam etiam erat velit scelerisque in dictum non. Imperdiet sed euismod nisi porta lorem mollis aliquam. Posuere morbi leo urna molestie at elementum. Pellentesque massa placerat duis ultricies lacus sed. Quis lectus nulla at volutpat diam ut venenatis tellus. Libero volutpat sed cras ornare arcu dui. Dolor sed viverra ipsum nunc aliquet. Lorem ipsum dolor sit amet consectetur adipiscing elit. Netus et malesuada fames ac turpis egestas maecenas. Nulla pellentesque dignissim enim sit amet venenatis urna. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Massa enim nec dui nunc mattis enim. Pulvinar pellentesque habitant morbi tristique senectus et netus. In egestas erat imperdiet sed euismod nisi porta. Nibh praesent tristique magna sit amet purus gravida quis blandit. Eu sem integer vitae justo. Felis donec et odio pellentesque diam volutpat.
                </p>
            </div>
            <Footer />
        </>
    )
}
